-- H2 (MODE=MySQL) test schema bootstrap
-- NOTE:
-- - H2는 ENGINE/COLLATE/COMMENT 미지원 → 제거
-- - AUTO_INCREMENT → IDENTITY
-- - datetime(6) → timestamp(6)
-- - json default (json_object()) 는 H2에서 그대로 안될 수 있어 기본값은 생략하고 NOT NULL만 유지 (엔티티 @PrePersist로 "{}" 보장)

drop table if exists settlement_line;
drop table if exists refund_settlement_link;
drop table if exists refund_event;
drop table if exists refund;
drop table if exists hold_event;
drop table if exists hold;
drop table if exists payment_event;
drop table if exists payment;
drop table if exists idempotency_record;
drop table if exists settlement;
drop table if exists settlement_batch;
drop table if exists orders;
drop table if exists audit_log;

-- 1) audit_log
create table audit_log (
                           audit_id      bigint generated by default as identity primary key,
                           request_id    char(36) not null,
                           occurred_at   timestamp(6) not null default current_timestamp(6),
                           actor_type    varchar(32) not null,
                           actor_id      varchar(32) not null,
                           action        varchar(64) not null,
                           entity_type   varchar(32) not null,
                           entity_id     char(36) not null,
                           status_before varchar(64),
                           status_after  varchar(64),
                           merchant_id   varchar(32),
                           meta_json     json not null
);

create index idx_audit_request_id  on audit_log(request_id);
create index idx_audit_entity_time on audit_log(entity_type, entity_id, occurred_at);
create index idx_audit_merchant_id on audit_log(merchant_id);
create index idx_audit_occurred_at on audit_log(occurred_at);

-- 2) orders
create table orders (
                        order_id     char(36) not null primary key,
                        merchant_id  varchar(32) not null,
                        buyer_id     varchar(32) not null,
                        item_name    varchar(255) not null,
                        amount       bigint not null,
                        currency     char(3) not null default 'KRW',
                        status       varchar(16) not null,
                        created_at   timestamp(6) not null,
                        updated_at   timestamp(6) not null
);

create index idx_orders_merchant_id on orders(merchant_id);
create index idx_orders_buyer_id    on orders(buyer_id);
create index idx_orders_status      on orders(status);
create index idx_orders_created_at  on orders(created_at);

-- 3) payment
create table payment (
                         payment_id        char(36) not null primary key,
                         order_id          char(36) not null,
                         merchant_id       varchar(32) not null,
                         buyer_id          varchar(32) not null,
                         currency          char(3) not null default 'KRW',
                         requested_amount  bigint not null,
                         captured_amount   bigint not null default 0,
                         status            varchar(32) not null,
                         created_at        timestamp(6) not null,
                         updated_at        timestamp(6) not null
);

create unique index uk_payment_order_id on payment(order_id);
create index idx_payment_order_id       on payment(order_id);
create index idx_payment_merchant_id    on payment(merchant_id);
create index idx_payment_buyer_id       on payment(buyer_id);
create index idx_payment_status         on payment(status);
create index idx_payment_created_at     on payment(created_at);

-- 4) payment_event
create table payment_event (
                               payment_event_id bigint generated by default as identity primary key,
                               payment_id       char(36) not null,
                               event_type       varchar(32) not null,
                               status_before    varchar(64),
                               status_after     varchar(64),
                               request_id       char(36) not null,
                               occurred_at      timestamp(6) not null default current_timestamp(6)
);

create unique index uk_payment_event_payment_type on payment_event(payment_id, event_type);
create index idx_payment_event_request_id         on payment_event(request_id);
create index idx_payment_event_payment_id_occurred_at on payment_event(payment_id, occurred_at);
create index idx_payment_event_type_occurred_at   on payment_event(event_type, occurred_at);

-- 5) idempotency_record
create table idempotency_record (
                                    idempotency_id   bigint generated by default as identity primary key,
                                    target_type      varchar(32) not null default 'PAY_ORDER',
                                    target_id        varchar(64) not null,
                                    idempotency_key  varchar(128) not null,
                                    payment_id       char(36),
                                    response_status  int null,
                                    request_id       char(36) not null,
                                    created_at       timestamp(3) not null default current_timestamp(3)
);

create unique index uk_idempotency       on idempotency_record(target_type, target_id, idempotency_key);
create index idx_idem_target            on idempotency_record(target_type, target_id);
create index idx_idem_request_id        on idempotency_record(request_id);
create index idx_idem_created_at        on idempotency_record(created_at);

-- 6) settlement_batch
create table settlement_batch (
                                  batch_id      bigint generated by default as identity primary key,
                                  batch_key     date not null,
                                  run_id        char(36) not null,
                                  triggered_by  varchar(50) not null,
                                  result        varchar(20) not null,
                                  request_id    char(36) not null,
                                  fail_reason   varchar(2000),
                                  created_at    timestamp(6) not null default current_timestamp(6),
                                  finished_at   timestamp(6)
);

create unique index uk_settlement_batch_key on settlement_batch(batch_key);
create index idx_settlement_batch_request_id on settlement_batch(request_id);
create index idx_settlement_batch_created_at on settlement_batch(created_at);

-- 7) settlement
create table settlement (
                            settlement_id       char(36) not null primary key,
                            settlement_no       varchar(50) not null,
                            batch_id            bigint not null,
                            merchant_id         varchar(32) not null,
                            status              varchar(32) not null,
                            base_date           date not null,
                            gross               bigint not null,
                            fee                 bigint not null,
                            vat                 bigint not null,
                            net                 bigint not null,
                            paid_requested_by   varchar(32),
                            paid_requested_at   timestamp(6),
                            paid_approved_by    varchar(32),
                            paid_approved_at    timestamp(6),
                            created_at          timestamp(6) not null,
                            updated_at          timestamp(6) not null
);

create unique index uk_settlement_merchant_base_date on settlement(merchant_id, base_date);
create index idx_settlement_status                on settlement(status);
create index idx_settlement_base_date             on settlement(base_date);
create index idx_settlement_batch                 on settlement(batch_id);
create index idx_settlement_status_base_date      on settlement(status, base_date);

-- 8) hold
create table hold (
                      hold_id               char(36) not null primary key,
                      settlement_id         char(36) not null,
                      status                varchar(32) not null,
                      requested_reason_code varchar(64) not null,
                      requested_comment     varchar(4000) not null,
                      created_by            varchar(32) not null,
                      created_at            timestamp(6) not null,
                      updated_at            timestamp(6) not null
);

create unique index uk_hold_settlement_id on hold(settlement_id);
create index idx_hold_status             on hold(status);
create index idx_hold_created_at         on hold(created_at);
create index idx_hold_updated_at         on hold(updated_at);

-- 9) hold_event
create table hold_event (
                            hold_event_id bigint generated by default as identity primary key,
                            hold_id       char(36) not null,
                            event_type    varchar(32) not null,
                            request_id    char(36) not null,
                            actor_type    varchar(32) not null,
                            actor_id      varchar(32) not null,
                            occurred_at   timestamp(6) not null default current_timestamp(6),
                            meta_json     json not null
);

create index idx_hold_event_request_id          on hold_event(request_id);
create index idx_hold_event_hold_id_occurred_at on hold_event(hold_id, occurred_at);
create index idx_hold_event_type                on hold_event(event_type);

-- 10) refund
create table refund (
                        refund_id     char(36) not null primary key,
                        payment_id    char(36) not null,
                        merchant_id   varchar(32) not null,
                        buyer_id      varchar(32) not null,
                        amount        bigint not null,
                        currency      char(3) not null default 'KRW',
                        status        varchar(32) not null,
                        reason_text   varchar(255) not null,
                        requested_at  timestamp(6) not null,
                        decided_at    timestamp(6),
                        created_at    timestamp(6) not null default current_timestamp(6),
                        updated_at    timestamp(6) not null default current_timestamp(6)
);

create unique index uk_refund_payment on refund(payment_id);
create index idx_refund_status        on refund(status);
create index idx_refund_merchant      on refund(merchant_id);
create index idx_refund_buyer         on refund(buyer_id);
create index idx_refund_requested_at  on refund(requested_at);

-- 11) refund_event
create table refund_event (
                              refund_event_id bigint generated by default as identity primary key,
                              refund_id       char(36) not null,
                              event_type      varchar(32) not null,
                              status_before   varchar(32),
                              status_after    varchar(32) not null,
                              request_id      char(36) not null,
                              actor_type      varchar(16) not null,
                              actor_id        varchar(32) not null,
                              occurred_at     timestamp(6) not null default current_timestamp(6)
);

create index idx_rfe_refund          on refund_event(refund_id);
create index idx_rfe_request         on refund_event(request_id);
create index idx_rfe_occurred        on refund_event(occurred_at);
create index idx_rfe_refund_occurred on refund_event(refund_id, occurred_at);

-- 12) refund_settlement_link
create table refund_settlement_link (
                                        refund_id      char(36) not null primary key,
                                        settlement_id  char(36) not null,
                                        created_at     timestamp(6) not null default current_timestamp(6)
);

create index idx_rsl_settlement on refund_settlement_link(settlement_id);

-- 13) settlement_line
create table settlement_line (
                                 settlement_line_id bigint generated by default as identity primary key,
                                 settlement_id      char(36) not null,
                                 payment_id         char(36) not null,
                                 line_type          varchar(20) not null,
                                 amount             bigint not null,
                                 created_at         timestamp(6) not null default current_timestamp(6)
);

create index idx_settlement_line_payment_id   on settlement_line(payment_id);
create index idx_settlement_line_settlement_id on settlement_line(settlement_id);
create index idx_settlement_line_type          on settlement_line(line_type);