-- test-only: AuditLog schema bootstrap for H2 (MySQL mode)
-- 목표: AuditLog 엔티티와 컬럼/제약을 최대한 1:1로 맞춰 테스트 재현성 고정

drop table if exists audit_log;

create table audit_log (
                           audit_id      bigint generated by default as identity primary key,

                           request_id    char(36) not null,
                           occurred_at   timestamp(6) not null,

                           actor_type    varchar(32) not null,
                           actor_id      varchar(32) not null,

                           action        varchar(64) not null,
                           entity_type   varchar(32) not null,
                           entity_id     char(36) not null,

                           status_before varchar(64),
                           status_after  varchar(64),

                           merchant_id   varchar(32),

    -- MySQL에서는 JSON, H2에서는 JSON 타입 호환이 애매하므로 CLOB으로 고정
                           meta_json     clob not null
);

create index idx_audit_request_id   on audit_log(request_id);
create index idx_audit_entity_time  on audit_log(entity_type, entity_id, occurred_at);
create index idx_audit_merchant_id  on audit_log(merchant_id);
create index idx_audit_occurred_at  on audit_log(occurred_at);